apiVersion: v1
kind: Service
metadata:
  name: vue-ambassador-service
spec:
  selector:
    app: vue-ambassador-pod
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 80
  type: ClusterIP
